clean: true
author: Kickstarter
author_url: https://github.com/Kickstarter/ios-ksapi
github_url: https://github.com/Kickstarter/ios-ksapi
module: KsApi
readme: README.md
skip_undocumented: false
xcodebuild_arguments:
  - -project
  - KsApi.xcodeproj
  - -scheme
  - KsApi-iOS
  - -destination,platform=iOS Simulator,name=iPhone 6,OS=iOS10.2
